services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - database

  server:
    image: nginx:alpine
    container_name: server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  database:
    image: docker/postgres/Dockerfile
    container_name: database
    environment:
      POSTGRES_DB: laravel-db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
